[package]
name = "prpr-avc"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.71"
tracing = "0.1.37"

[package.metadata.ffmpeg]
version = "4.4"
lib_dir = "C:\\msys64\\mingw64\\lib"
include_dir = "C:\\msys64\\mingw64\\include"
