name: Build Phira APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Set up Android NDK
        run: |
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -O ndk.zip
          unzip ndk.zip -d $HOME/ndk
          echo "export ANDROID_NDK=$HOME/ndk/android-ndk-r21e" >> $GITHUB_ENV

      - name: Install Rust toolchain for Android
        run: rustup target add aarch64-linux-android armv7-linux-androideabi

      - name: Install dependencies
        run: |
          cargo build --target aarch64-linux-android
          cargo build --target armv7-linux-androideabi

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: phira-apk
          path: app/build/outputs/apk/release/app-release.apk
