name: Build Phira APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip clang libzstd-dev
          sudo apt-get install libzstd-dev

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: $HOME/android-sdk
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Download and set up Android SDK
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"

      - name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Install Rust toolchain for Android
        run: |
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi

      - name: Install cargo-ndk
        run: |
          cargo install cargo-ndk

      - name: Set up Android NDK
        run: |
          echo "export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "export PATH=\$PATH:\$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

      - name: Build the Rust project for Android
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          cargo ndk -t aarch64-linux-android -o ./target/ndk build
          cargo ndk -t armv7-linux-androideabi -o ./target/ndk build

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: phira-apk
          path: app/build/outputs/apk/release/app-release.apk
