name: Build Phira APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Install Android Studio
        run: |
          wget https://dl.google.com/dl/android/studio/ide-zips/2022.2.1.19/android-studio-2022.2.1.19-linux.tar.gz -O android-studio.tar.gz
          tar -xvf android-studio.tar.gz
          sudo mv android-studio /usr/local/
          export PATH=$PATH:/usr/local/android-studio/bin
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: 'commandlinetools-6609375_latest'
      
      - name: Install Android SDK packages
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"

      - name: Set up Android NDK
        run: echo "export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Install Rust toolchain for Android
        run: |
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi

      - name: Build the Rust project for Android
        run: |
          export NDK_HOME=$ANDROID_NDK_HOME
          cargo build --target aarch64-linux-android --release
          cargo build --target armv7-linux-androideabi --release

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: phira-apk
          path: app/build/outputs/apk/release/app-release.apk
